# GitGuardian configuration for ggshield
# This file configures which files and secrets to ignore during scanning

# Ignore specific file patterns
paths-ignore:
  # Mock certificates for testing (these are intentionally committed test data)
  - "**/mock_certificates/**/*.key"
  - "**/mock_certificates/**/*.crt"
  - "**/mock_certificates/**/*.pem"
  - "**/constants/mockCertificates.ts"
  - "common/src/mock_certificates/**"
  - "common/src/mock_certificates/aadhaar/mockAadhaarCert.ts"
  - "common/src/utils/passports/genMockIdDoc.ts"

  # Test data files
  - "**/test/**/*.key"
  - "**/test/**/*.crt"
  - "**/test/**/*.pem"
  - "**/tests/**/*.key"
  - "**/tests/**/*.crt"
  - "**/tests/**/*.pem"

  # Mock data files
  - "**/mock/**/*.key"
  - "**/mock/**/*.crt"
  - "**/mock/**/*.pem"

  # Demo app test data
  - "**/demo-app/**/mock/**"
  - "**/demo-app/**/test-data/**"
  - "**/test-data/**"
  - "**/mock-data/**"

  # Generated test files
  - "**/generated/**/*.key"
  - "**/generated/**/*.crt"
  - "**/generated/**/*.pem"

  # iOS frameworks and build artifacts
  - "**/*.xcframework"
  - "**/NFCPassportReader.xcframework/**"
  - "**/OpenSSL.xcframework/**"
  - "**/SelfSDK.xcframework/**"
  - "**/packages/mobile-sdk-alpha/ios/Frameworks/**"
  - "**/packages/mobile-sdk-alpha/ios/SelfSDK/**"
# Ignore specific secret types for mock files
secrets-ignore:
  - "Generic Private Key" # For mock certificate keys
  - "Generic Certificate" # For mock certificates
  - "RSA Private Key" # For mock RSA keys
  - "EC Private Key" # For mock EC keys


secret:
  ignored_matches:
  - match: 2036b4e50ad3042969b290e354d9864465107a14de6f5a36d49f81ea8290def8
    name: prebuilt-ios-arm64-apple-ios.private.swiftinterface
  ignored_paths:
  - '**/packages/mobile-sdk-alpha/ios/Frameworks/**'
  - '**/OpenSSL.xcframework/**'
  - '**/demo-app/**/mock/**'
  - common/src/mock_certificates/aadhaar/mockAadhaarCert.ts
  - '**/NFCPassportReader.xcframework/**'
  - common/src/utils/passports/genMockIdDoc.ts
  - '**/tests/**/*.crt'
  - '**/mock_certificates/**/*.crt'
  - '**/mock_certificates/**/*.key'
  - '**/demo-app/**/test-data/**'
  - '**/generated/**/*.key'
  - '**/SelfSDK.xcframework/**'
  - '**/mock/**/*.crt'
  - '**/generated/**/*.crt'
  - '**/test/**/*.key'
  - '**/mock/**/*.key'
  - '**/test/**/*.crt'
  - '**/test/**/*.pem'
  - '**/constants/mockCertificates.ts'
  - '**/mock/**/*.pem'
  - '**/mock_certificates/**/*.pem'
  - '**/mock-data/**'
  - '**/packages/mobile-sdk-alpha/ios/SelfSDK/**'
  - '**/tests/**/*.key'
  - '**/generated/**/*.pem'
  - '**/tests/**/*.pem'
  - '**/test-data/**'
  - common/src/mock_certificates/**
  - '**/*.xcframework'
version: 2
