name: Get Version from package.json

description: "Gets the version from package.json and sets it as an environment variable"

inputs:
  app_path:
    description: "Path to the app directory"
    required: true

outputs:
  version:
    description: "Extracted app version from package.json"
    value: ${{ steps.get-version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Get version from package.json
      id: get-version
      shell: bash
      run: |
        VERSION=$(node -p "require('${{ inputs.app_path }}/package.json').version")
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "VERSION=$VERSION" >> $GITHUB_ENV
