name: Block non-staging PRs to main

on:
  pull_request:
    branches: [main]

jobs:
  check-source:
    runs-on: ubuntu-latest
    steps:
      - name: Block PRs not from staging
        run: |
          if [[ "${{ github.head_ref }}" != "staging" ]]; then
            echo "You can only merge from staging to main."
            exit 1
          fi
