name: Circuits CI
on:
  push:
    branches:
      - dev
      - main
      - openpassportv2
    paths:
      - "circuits/**"
      - "common/**"
  pull_request:
    branches:
      - dev
      - main
      - openpassportv2
    paths:
      - "circuits/**"
      - "common/**"
jobs:
  run_circuit_tests:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    environment: development
    permissions:
      contents: read
    env:
      CIRCOM_VERSION: "2.1.9"
      CIRCOM_SHA256: "e5575829252d763b7818049df9de2ef9304df834697de77fa63ce7babc23c967"
    steps:
      - uses: actions/checkout@v4

      # Circom installation from https://github.com/erhant/circomkit/blob/main/.github/workflows/tests.yml
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes \
            build-essential \
            libgmp-dev \
            libsodium-dev \
            nasm \
            nlohmann-json3-dev

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Restore Circom binary
        id: circom-cache
        uses: actions/cache/restore@v4
        with:
          path: ~/.cache/circom
          key: circom-v2.1.9

      - name: Download Circom Binary v2.1.9
        if: steps.circom-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.cache/circom
          wget -qO ~/.cache/circom/circom https://github.com/iden3/circom/releases/download/v${{ env.CIRCOM_VERSION }}/circom-linux-amd64
          chmod +x ~/.cache/circom/circom
          # Verify checksum - SHA256 for circom v2.1.9 linux-amd64
          echo "${{ env.CIRCOM_SHA256 }}  ~/.cache/circom/circom" | sha256sum -c -

      - name: Save Circom cache
        if: steps.circom-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: ~/.cache/circom
          key: circom-v2.1.9

      - name: Verify Circom checksum (cache hit)
        if: steps.circom-cache.outputs.cache-hit == 'true'
        run: |
          echo "${{ env.CIRCOM_SHA256 }}  ~/.cache/circom/circom" | sha256sum -c -

      - name: Add Circom to PATH
        run: echo "$HOME/.cache/circom" >> "$GITHUB_PATH"

      - name: Print Circom version
        run: circom --version

      - name: Install Yarn dependencies
        uses: ./.github/actions/yarn-install
        with:
          working_directory: circuits

      - name: Run lint
        run: yarn workspace @selfxyz/circuits lint
      - name: Run Tests (Circuits)
        env:
          FULL_TEST_SUITE: false
        run: yarn workspace @selfxyz/circuits test
