name: Mobile CI
env:
  # Build environment versions
  NODE_VERSION: 22
  RUBY_VERSION: 3.2
  JAVA_VERSION: 17
  # Path configuration
  WORKSPACE: ${{ github.workspace }}
  APP_PATH: ${{ github.workspace }}/app
on:
  push:
    paths:
      - "common/**"
      - "app/**"
      - ".github/workflows/app.yml"
      - ".github/actions/**"

jobs:
  lint:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: |
            .yarn/cache
            node_modules
            app/node_modules
          key: ${{ runner.os }}-node${{ env.NODE_VERSION }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node${{ env.NODE_VERSION }}-yarn-
      - name: Install Dependencies
        uses: ./.github/actions/yarn-install
      - name: Build Dependencies
        run: yarn build:deps
        working-directory: ./app
      - name: Run linter
        run: yarn lint
        working-directory: ./app
      - name: Run prettier
        run: yarn fmt
        working-directory: ./app

  test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: |
            .yarn/cache
            node_modules
            app/node_modules
          key: ${{ runner.os }}-node${{ env.NODE_VERSION }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node${{ env.NODE_VERSION }}-yarn-
      - name: Install Dependencies
        uses: ./.github/actions/yarn-install

      - name: Build
        run: yarn build:deps
        working-directory: ./app
      - name: Test
        run: yarn test
        working-directory: ./app
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          # some cocoapods won't compile with xcode 16.3
          xcode-version: "16.2"

      - uses: actions/checkout@v4
      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: |
            .yarn/cache
            node_modules
            app/node_modules
          key: ${{ runner.os }}-node${{ env.NODE_VERSION }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node${{ env.NODE_VERSION }}-yarn-
      - name: Cache Ruby Bundler
        uses: actions/cache@v4
        with:
          path: app/vendor/bundle
          key: ${{ runner.os }}-ruby${{ env.RUBY_VERSION }}-gems-${{ hashFiles('app/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-ruby${{ env.RUBY_VERSION }}-gems-
      - name: Cache CocoaPods
        uses: actions/cache@v4
        with:
          path: app/ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('app/ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('app/android/**/gradle-wrapper.properties', 'app/android/**/gradle-wrapper.jar') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Install Mobile Dependencies
        uses: ./.github/actions/mobile-setup
        with:
          app_path: ${{ env.APP_PATH }}
          node_version: ${{ env.NODE_VERSION }}
          ruby_version: ${{ env.RUBY_VERSION }}
          workspace: ${{ env.WORKSPACE }}
      - name: Install And Build
        run: yarn install-app
        working-directory: ./app
